/********************************************************************
* src/E14CosmicHoughDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/E14CosmicHoughDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableE14CosmicHoughDict();
extern void G__cpp_setup_inheritanceE14CosmicHoughDict();
extern void G__cpp_setup_typetableE14CosmicHoughDict();
extern void G__cpp_setup_memvarE14CosmicHoughDict();
extern void G__cpp_setup_globalE14CosmicHoughDict();
extern void G__cpp_setup_memfuncE14CosmicHoughDict();
extern void G__cpp_setup_funcE14CosmicHoughDict();
extern void G__set_cpp_environmentE14CosmicHoughDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/E14CosmicHough.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__E14CosmicHoughDictLN_TClass;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TBuffer;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TMemberInspector;
extern G__linked_taginfo G__E14CosmicHoughDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TF1;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TH2D;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TGraph;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TGraphErrors;
extern G__linked_taginfo G__E14CosmicHoughDictLN_TLine;
extern G__linked_taginfo G__E14CosmicHoughDictLN_E14CosmicHough;

/* STUB derived class for protected member access */
