/********************************************************************
* src/CsIImageDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/CsIImageDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCsIImageDict();
extern void G__cpp_setup_inheritanceCsIImageDict();
extern void G__cpp_setup_typetableCsIImageDict();
extern void G__cpp_setup_memvarCsIImageDict();
extern void G__cpp_setup_globalCsIImageDict();
extern void G__cpp_setup_memfuncCsIImageDict();
extern void G__cpp_setup_funcCsIImageDict();
extern void G__set_cpp_environmentCsIImageDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/CsIImage.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CsIImageDictLN_TClass;
extern G__linked_taginfo G__CsIImageDictLN_TBuffer;
extern G__linked_taginfo G__CsIImageDictLN_TMemberInspector;
extern G__linked_taginfo G__CsIImageDictLN_TObject;
extern G__linked_taginfo G__CsIImageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CsIImageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CsIImageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CsIImageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CsIImageDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CsIImageDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CsIImageDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CsIImageDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CsIImageDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CsIImageDictLN_TH2D;
extern G__linked_taginfo G__CsIImageDictLN_TBox;
extern G__linked_taginfo G__CsIImageDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__CsIImageDictLN_IDHandler;
extern G__linked_taginfo G__CsIImageDictLN_vectorlEmaplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgRcOallocatorlEmaplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__CsIImageDictLN_reverse_iteratorlEvectorlEmaplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgRcOallocatorlEmaplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CsIImageDictLN_CsIImage;

/* STUB derived class for protected member access */
