/********************************************************************
* src/E14CalibratorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/E14CalibratorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableE14CalibratorDict();
extern void G__cpp_setup_inheritanceE14CalibratorDict();
extern void G__cpp_setup_typetableE14CalibratorDict();
extern void G__cpp_setup_memvarE14CalibratorDict();
extern void G__cpp_setup_globalE14CalibratorDict();
extern void G__cpp_setup_memfuncE14CalibratorDict();
extern void G__cpp_setup_funcE14CalibratorDict();
extern void G__set_cpp_environmentE14CalibratorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/E14Calibrator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__E14CalibratorDictLN_TClass;
extern G__linked_taginfo G__E14CalibratorDictLN_TBuffer;
extern G__linked_taginfo G__E14CalibratorDictLN_TMemberInspector;
extern G__linked_taginfo G__E14CalibratorDictLN_TObject;
extern G__linked_taginfo G__E14CalibratorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__E14CalibratorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14CalibratorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__E14CalibratorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14CalibratorDictLN_E14Calibrator;

/* STUB derived class for protected member access */
