/********************************************************************
* src/CC03PolyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/CC03PolyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCC03PolyDict();
extern void G__cpp_setup_inheritanceCC03PolyDict();
extern void G__cpp_setup_typetableCC03PolyDict();
extern void G__cpp_setup_memvarCC03PolyDict();
extern void G__cpp_setup_globalCC03PolyDict();
extern void G__cpp_setup_memfuncCC03PolyDict();
extern void G__cpp_setup_funcCC03PolyDict();
extern void G__set_cpp_environmentCC03PolyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/CC03Poly.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CC03PolyDictLN_TClass;
extern G__linked_taginfo G__CC03PolyDictLN_TBuffer;
extern G__linked_taginfo G__CC03PolyDictLN_TMemberInspector;
extern G__linked_taginfo G__CC03PolyDictLN_TObject;
extern G__linked_taginfo G__CC03PolyDictLN_TNamed;
extern G__linked_taginfo G__CC03PolyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CC03PolyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CC03PolyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CC03PolyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CC03PolyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CC03PolyDictLN_TAttLine;
extern G__linked_taginfo G__CC03PolyDictLN_TAttFill;
extern G__linked_taginfo G__CC03PolyDictLN_TAttMarker;
extern G__linked_taginfo G__CC03PolyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CC03PolyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CC03PolyDictLN_TH1;
extern G__linked_taginfo G__CC03PolyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CC03PolyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CC03PolyDictLN_TH2;
extern G__linked_taginfo G__CC03PolyDictLN_TH2Poly;
extern G__linked_taginfo G__CC03PolyDictLN_CC03Poly;

/* STUB derived class for protected member access */
