/********************************************************************
* src/CC03_ModuleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/CC03_ModuleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCC03_ModuleDict();
extern void G__cpp_setup_inheritanceCC03_ModuleDict();
extern void G__cpp_setup_typetableCC03_ModuleDict();
extern void G__cpp_setup_memvarCC03_ModuleDict();
extern void G__cpp_setup_globalCC03_ModuleDict();
extern void G__cpp_setup_memfuncCC03_ModuleDict();
extern void G__cpp_setup_funcCC03_ModuleDict();
extern void G__set_cpp_environmentCC03_ModuleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/CC03_Module.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CC03_ModuleDictLN_TClass;
extern G__linked_taginfo G__CC03_ModuleDictLN_TBuffer;
extern G__linked_taginfo G__CC03_ModuleDictLN_TMemberInspector;
extern G__linked_taginfo G__CC03_ModuleDictLN_TObject;
extern G__linked_taginfo G__CC03_ModuleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CC03_ModuleDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CC03_ModuleDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CC03_ModuleDictLN_TH2Poly;
extern G__linked_taginfo G__CC03_ModuleDictLN_TBox;
extern G__linked_taginfo G__CC03_ModuleDictLN_CC03_Module;

/* STUB derived class for protected member access */
