/********************************************************************
* src/CsI_ModuleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/CsI_ModuleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCsI_ModuleDict();
extern void G__cpp_setup_inheritanceCsI_ModuleDict();
extern void G__cpp_setup_typetableCsI_ModuleDict();
extern void G__cpp_setup_memvarCsI_ModuleDict();
extern void G__cpp_setup_globalCsI_ModuleDict();
extern void G__cpp_setup_memfuncCsI_ModuleDict();
extern void G__cpp_setup_funcCsI_ModuleDict();
extern void G__set_cpp_environmentCsI_ModuleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/CsI_Module.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CsI_ModuleDictLN_TClass;
extern G__linked_taginfo G__CsI_ModuleDictLN_TBuffer;
extern G__linked_taginfo G__CsI_ModuleDictLN_TMemberInspector;
extern G__linked_taginfo G__CsI_ModuleDictLN_TObject;
extern G__linked_taginfo G__CsI_ModuleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CsI_ModuleDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CsI_ModuleDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CsI_ModuleDictLN_TH2Poly;
extern G__linked_taginfo G__CsI_ModuleDictLN_TBox;
extern G__linked_taginfo G__CsI_ModuleDictLN_CsI_Module;

/* STUB derived class for protected member access */
