/********************************************************************
* src/FBPolyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/FBPolyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFBPolyDict();
extern void G__cpp_setup_inheritanceFBPolyDict();
extern void G__cpp_setup_typetableFBPolyDict();
extern void G__cpp_setup_memvarFBPolyDict();
extern void G__cpp_setup_globalFBPolyDict();
extern void G__cpp_setup_memfuncFBPolyDict();
extern void G__cpp_setup_funcFBPolyDict();
extern void G__set_cpp_environmentFBPolyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/FBPoly.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FBPolyDictLN_TClass;
extern G__linked_taginfo G__FBPolyDictLN_TBuffer;
extern G__linked_taginfo G__FBPolyDictLN_TMemberInspector;
extern G__linked_taginfo G__FBPolyDictLN_TObject;
extern G__linked_taginfo G__FBPolyDictLN_TNamed;
extern G__linked_taginfo G__FBPolyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FBPolyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FBPolyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FBPolyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FBPolyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FBPolyDictLN_TAttLine;
extern G__linked_taginfo G__FBPolyDictLN_TAttFill;
extern G__linked_taginfo G__FBPolyDictLN_TAttMarker;
extern G__linked_taginfo G__FBPolyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FBPolyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FBPolyDictLN_TH1;
extern G__linked_taginfo G__FBPolyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__FBPolyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__FBPolyDictLN_TH2;
extern G__linked_taginfo G__FBPolyDictLN_TH2Poly;
extern G__linked_taginfo G__FBPolyDictLN_FBPoly;

/* STUB derived class for protected member access */
