/********************************************************************
* src/MBPolyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/MBPolyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMBPolyDict();
extern void G__cpp_setup_inheritanceMBPolyDict();
extern void G__cpp_setup_typetableMBPolyDict();
extern void G__cpp_setup_memvarMBPolyDict();
extern void G__cpp_setup_globalMBPolyDict();
extern void G__cpp_setup_memfuncMBPolyDict();
extern void G__cpp_setup_funcMBPolyDict();
extern void G__set_cpp_environmentMBPolyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/MBPoly.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MBPolyDictLN_TClass;
extern G__linked_taginfo G__MBPolyDictLN_TBuffer;
extern G__linked_taginfo G__MBPolyDictLN_TMemberInspector;
extern G__linked_taginfo G__MBPolyDictLN_TObject;
extern G__linked_taginfo G__MBPolyDictLN_TNamed;
extern G__linked_taginfo G__MBPolyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MBPolyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MBPolyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MBPolyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MBPolyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MBPolyDictLN_TAttLine;
extern G__linked_taginfo G__MBPolyDictLN_TAttFill;
extern G__linked_taginfo G__MBPolyDictLN_TAttMarker;
extern G__linked_taginfo G__MBPolyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MBPolyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MBPolyDictLN_TH1;
extern G__linked_taginfo G__MBPolyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MBPolyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MBPolyDictLN_TH2;
extern G__linked_taginfo G__MBPolyDictLN_TH2Poly;
extern G__linked_taginfo G__MBPolyDictLN_MBPoly;

/* STUB derived class for protected member access */
