/********************************************************************
* src/OEVPolyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/OEVPolyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableOEVPolyDict();
extern void G__cpp_setup_inheritanceOEVPolyDict();
extern void G__cpp_setup_typetableOEVPolyDict();
extern void G__cpp_setup_memvarOEVPolyDict();
extern void G__cpp_setup_globalOEVPolyDict();
extern void G__cpp_setup_memfuncOEVPolyDict();
extern void G__cpp_setup_funcOEVPolyDict();
extern void G__set_cpp_environmentOEVPolyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/OEVPoly.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OEVPolyDictLN_TClass;
extern G__linked_taginfo G__OEVPolyDictLN_TBuffer;
extern G__linked_taginfo G__OEVPolyDictLN_TMemberInspector;
extern G__linked_taginfo G__OEVPolyDictLN_TObject;
extern G__linked_taginfo G__OEVPolyDictLN_TNamed;
extern G__linked_taginfo G__OEVPolyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__OEVPolyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OEVPolyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__OEVPolyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OEVPolyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__OEVPolyDictLN_TAttLine;
extern G__linked_taginfo G__OEVPolyDictLN_TAttFill;
extern G__linked_taginfo G__OEVPolyDictLN_TAttMarker;
extern G__linked_taginfo G__OEVPolyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__OEVPolyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__OEVPolyDictLN_TH1;
extern G__linked_taginfo G__OEVPolyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__OEVPolyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__OEVPolyDictLN_TH2;
extern G__linked_taginfo G__OEVPolyDictLN_TH2Poly;
extern G__linked_taginfo G__OEVPolyDictLN_OEVPoly;

/* STUB derived class for protected member access */
