/********************************************************************
* src/SemiOfflineHistDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/SemiOfflineHistDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSemiOfflineHistDict();
extern void G__cpp_setup_inheritanceSemiOfflineHistDict();
extern void G__cpp_setup_typetableSemiOfflineHistDict();
extern void G__cpp_setup_memvarSemiOfflineHistDict();
extern void G__cpp_setup_globalSemiOfflineHistDict();
extern void G__cpp_setup_memfuncSemiOfflineHistDict();
extern void G__cpp_setup_funcSemiOfflineHistDict();
extern void G__set_cpp_environmentSemiOfflineHistDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/SemiOfflineHist.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SemiOfflineHistDictLN_TClass;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TBuffer;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TMemberInspector;
extern G__linked_taginfo G__SemiOfflineHistDictLN_string;
extern G__linked_taginfo G__SemiOfflineHistDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TFile;
extern G__linked_taginfo G__SemiOfflineHistDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TH1F;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TH2F;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TGraphErrors;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TCanvas;
extern G__linked_taginfo G__SemiOfflineHistDictLN_TBox;
extern G__linked_taginfo G__SemiOfflineHistDictLN_E14Mapper;
extern G__linked_taginfo G__SemiOfflineHistDictLN_SemiOfflineHist;

/* STUB derived class for protected member access */
