/********************************************************************
* src/E14DataReadVMEDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/E14DataReadVMEDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableE14DataReadVMEDict();
extern void G__cpp_setup_inheritanceE14DataReadVMEDict();
extern void G__cpp_setup_typetableE14DataReadVMEDict();
extern void G__cpp_setup_memvarE14DataReadVMEDict();
extern void G__cpp_setup_globalE14DataReadVMEDict();
extern void G__cpp_setup_memfuncE14DataReadVMEDict();
extern void G__cpp_setup_funcE14DataReadVMEDict();
extern void G__set_cpp_environmentE14DataReadVMEDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/E14DataReadVME.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__E14DataReadVMEDictLN_TClass;
extern G__linked_taginfo G__E14DataReadVMEDictLN_TBuffer;
extern G__linked_taginfo G__E14DataReadVMEDictLN_TMemberInspector;
extern G__linked_taginfo G__E14DataReadVMEDictLN_string;
extern G__linked_taginfo G__E14DataReadVMEDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_TFile;
extern G__linked_taginfo G__E14DataReadVMEDictLN_TTree;
extern G__linked_taginfo G__E14DataReadVMEDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__E14DataReadVMEDictLN_E14RawData;
extern G__linked_taginfo G__E14DataReadVMEDictLN_E14DataReadVME;

/* STUB derived class for protected member access */
