/********************************************************************
* src/PulseGeneratorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/PulseGeneratorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePulseGeneratorDict();
extern void G__cpp_setup_inheritancePulseGeneratorDict();
extern void G__cpp_setup_typetablePulseGeneratorDict();
extern void G__cpp_setup_memvarPulseGeneratorDict();
extern void G__cpp_setup_globalPulseGeneratorDict();
extern void G__cpp_setup_memfuncPulseGeneratorDict();
extern void G__cpp_setup_funcPulseGeneratorDict();
extern void G__set_cpp_environmentPulseGeneratorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/PulseGenerator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PulseGeneratorDictLN_TClass;
extern G__linked_taginfo G__PulseGeneratorDictLN_TBuffer;
extern G__linked_taginfo G__PulseGeneratorDictLN_TMemberInspector;
extern G__linked_taginfo G__PulseGeneratorDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PulseGeneratorDictLN_TF1;
extern G__linked_taginfo G__PulseGeneratorDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PulseGeneratorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PulseGeneratorDictLN_PulseGenerator;

/* STUB derived class for protected member access */
