/********************************************************************
* src/HoughCsIDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/HoughCsIDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHoughCsIDict();
extern void G__cpp_setup_inheritanceHoughCsIDict();
extern void G__cpp_setup_typetableHoughCsIDict();
extern void G__cpp_setup_memvarHoughCsIDict();
extern void G__cpp_setup_globalHoughCsIDict();
extern void G__cpp_setup_memfuncHoughCsIDict();
extern void G__cpp_setup_funcHoughCsIDict();
extern void G__set_cpp_environmentHoughCsIDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/HoughCsI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HoughCsIDictLN_TClass;
extern G__linked_taginfo G__HoughCsIDictLN_TBuffer;
extern G__linked_taginfo G__HoughCsIDictLN_TMemberInspector;
extern G__linked_taginfo G__HoughCsIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HoughCsIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HoughCsIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HoughCsIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HoughCsIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HoughCsIDictLN_TF1;
extern G__linked_taginfo G__HoughCsIDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HoughCsIDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HoughCsIDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HoughCsIDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HoughCsIDictLN_TH2D;
extern G__linked_taginfo G__HoughCsIDictLN_TGraph;
extern G__linked_taginfo G__HoughCsIDictLN_TGraphErrors;
extern G__linked_taginfo G__HoughCsIDictLN_TLine;
extern G__linked_taginfo G__HoughCsIDictLN_HoughCsI;

/* STUB derived class for protected member access */
