/********************************************************************
* src/StyleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/StyleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStyleDict();
extern void G__cpp_setup_inheritanceStyleDict();
extern void G__cpp_setup_typetableStyleDict();
extern void G__cpp_setup_memvarStyleDict();
extern void G__cpp_setup_globalStyleDict();
extern void G__cpp_setup_memfuncStyleDict();
extern void G__cpp_setup_funcStyleDict();
extern void G__set_cpp_environmentStyleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/Style.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StyleDictLN_TStyle;

/* STUB derived class for protected member access */
