/********************************************************************
* src/WaveformFitterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/WaveformFitterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWaveformFitterDict();
extern void G__cpp_setup_inheritanceWaveformFitterDict();
extern void G__cpp_setup_typetableWaveformFitterDict();
extern void G__cpp_setup_memvarWaveformFitterDict();
extern void G__cpp_setup_globalWaveformFitterDict();
extern void G__cpp_setup_memfuncWaveformFitterDict();
extern void G__cpp_setup_funcWaveformFitterDict();
extern void G__set_cpp_environmentWaveformFitterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./include/WaveformFitter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WaveformFitterDictLN_TClass;
extern G__linked_taginfo G__WaveformFitterDictLN_TBuffer;
extern G__linked_taginfo G__WaveformFitterDictLN_TMemberInspector;
extern G__linked_taginfo G__WaveformFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WaveformFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WaveformFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WaveformFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WaveformFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WaveformFitterDictLN_TF1;
extern G__linked_taginfo G__WaveformFitterDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__WaveformFitterDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__WaveformFitterDictLN_TGraph;
extern G__linked_taginfo G__WaveformFitterDictLN_WaveformFitter;

/* STUB derived class for protected member access */
